name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: sudo apt-get install -y curl

      - name: Prueba básica
        run: echo "✅ Pipeline corriendo bien"
